name = "MyExample"
uuid = "5c2e358b-3d27-42e4-bd7f-4dbdaea91598"
authors = ["Blake Johnson <blakeejohnson39@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
